export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const CREATE_BOARD = 'CREATE_BOARD'
export const FETCH_TODOS = 'FETCH_TODOS'
